### ISSUE TITLE
插件运行报错

### ISSUE THREAD

**Issue by ElainaFanBoy** [ye-tutu/nonebot_plugin_everyfurry#3]
from CrawlerFurry import crawler_furry
ModuleNotFoundError: No module named 'CrawlerFurry'

from DecisionSource import decision
ModuleNotFoundError: No module named 'DecisionSource'

插件用不了，还会再更新吗（好喜欢兽兽的说），感觉用不了好可惜

**Comment by Nenot233** [comment]
pip install CrawlerFurry
pip install DecisionSource
python -m pip install CrawlerFurry
python -m pip install DecisionSource
是缺少依赖

**Comment by NanakoOfficial** [comment]
> 

草，这两个依赖我在清华yuan源li'm里面mei'y没有sou'd搜到

**Comment by ElainaFanBoy** [comment]
> pip install CrawlerFurry pip install DecisionSource python -m pip install CrawlerFurry python -m pip install DecisionSource 是缺少依赖

草，这两个依赖我在清华源里都没有搜到
